[package]
name = "fflogs"
version = "0.1.0"
edition = "2024"

[dependencies]
compact_str = { version = "0.8", features = ["serde"] }
reqwest = { version = "0.12", features = ["json"] }
serde = { version = "1.0", features = ["derive"] }
serde_json = "1"
serde_path_to_error = "0.1"
serde_qs = "0.13"
serde_with = "3.12"
smallvec = { version = "=2.0.0-alpha.10", features = ["serde"] }
strum = { version = "0.26", features = ["derive"] }
thiserror = { version = "2" }
tracing = { version = "0.1", features = ["log"] }

[dev-dependencies]
ctor = "0.2"
tokio = { version = "1", features = ["full"] }
tracing-subscriber = { version = "0.3", features = ["env-filter"] }

[features]
brotli = ["reqwest/brotli"]
deflate = ["reqwest/deflate"]
gzip = ["reqwest/gzip"]

[lints.rust]
#missing_docs = "warn"